AWSTemplateFormatVersion: "2010-09-09"
Description:

Parameters:
  InstanceTypeParameter:
    Description: WebServer EC2
    Type: AWS::SSM::Parameter::Value<String>
    Default: /dev/ec2/instanceType

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
    DependsOn: MyS3Bucket
