AWSTemplateFormatVersion: "2010-09-09"
Description:
Resources:
  MyFirstS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: "This is a custom name to my bucket which will replace and create new resource"
